# Generated by Django 3.2 on 2022-03-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0006_alter_songs_dlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='org_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('dlink', models.TextField()),
                ('alb', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='index.album')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgm.org_score')),
                ('remixer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgm.channel')),
            ],
        ),
    ]
