# Generated by Django 3.2 on 2021-10-19 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=50)),
                ('spic', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('lyrics', models.TextField(blank=True)),
                ('lang', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='index.language')),
            ],
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('displaypic', models.CharField(max_length=255)),
                ('Playlist', models.ManyToManyField(to='index.songs')),
            ],
        ),
    ]
