# Generated by Django 3.2 on 2021-10-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='alb',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to='index.album'),
        ),
    ]
