# Generated by Django 3.2 on 2021-10-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_songs_alb'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='dlink',
            field=models.CharField(default='True', max_length=255),
        ),
    ]
